generator:
  features:
    enable:
      # Enables paths client generation
      - "paths/client"
      # Enables paths server generation
      - "paths/server"
      # Enables validation of client requests
      - "client/request/validation"
      # Enables validation of server responses
      - "server/response/validation"
      # Enables OpenTelemetry integration
      - "ogen/otel"
  ignore_not_implemented: ["all"]
  convenient_errors: "auto"
