// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AdminUsersCreateOperation        OperationName = "AdminUsersCreate"
	AdminUsersDestroyOperation       OperationName = "AdminUsersDestroy"
	AdminUsersListOperation          OperationName = "AdminUsersList"
	AdminUsersPartialUpdateOperation OperationName = "AdminUsersPartialUpdate"
	AdminUsersRetrieveOperation      OperationName = "AdminUsersRetrieve"
	AdminUsersUpdateOperation        OperationName = "AdminUsersUpdate"
	FacilitiesCreateOperation        OperationName = "FacilitiesCreate"
	FacilitiesDestroyOperation       OperationName = "FacilitiesDestroy"
	FacilitiesListOperation          OperationName = "FacilitiesList"
	FacilitiesPartialUpdateOperation OperationName = "FacilitiesPartialUpdate"
	FacilitiesRetrieveOperation      OperationName = "FacilitiesRetrieve"
	FacilitiesUpdateOperation        OperationName = "FacilitiesUpdate"
	MeRetrieveOperation              OperationName = "MeRetrieve"
)
