// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v1/"

			if l := len("/api/v1/"); len(elem) >= l && elem[0:l] == "/api/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "admin/users/"

				if l := len("admin/users/"); len(elem) >= l && elem[0:l] == "admin/users/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleAdminUsersListRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleAdminUsersCreateRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}
				// Param: "id"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleAdminUsersDestroyRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleAdminUsersRetrieveRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleAdminUsersUpdateRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "DELETE,GET,PUT")
						}

						return
					}

				}

			case 'f': // Prefix: "facilities/"

				if l := len("facilities/"); len(elem) >= l && elem[0:l] == "facilities/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleFacilitiesListRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleFacilitiesCreateRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}
				// Param: "id"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleFacilitiesDestroyRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleFacilitiesRetrieveRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleFacilitiesPartialUpdateRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleFacilitiesUpdateRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "DELETE,GET,PATCH,PUT")
						}

						return
					}

				}

			case 'm': // Prefix: "me/"

				if l := len("me/"); len(elem) >= l && elem[0:l] == "me/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleMeRetrieveRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v1/"

			if l := len("/api/v1/"); len(elem) >= l && elem[0:l] == "/api/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "admin/users/"

				if l := len("admin/users/"); len(elem) >= l && elem[0:l] == "admin/users/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = AdminUsersListOperation
						r.summary = "List all users"
						r.operationID = "admin_users_list"
						r.pathPattern = "/api/v1/admin/users/"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = AdminUsersCreateOperation
						r.summary = "Create a new user"
						r.operationID = "admin_users_create"
						r.pathPattern = "/api/v1/admin/users/"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				// Param: "id"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = AdminUsersDestroyOperation
							r.summary = "Delete a user (admin only)"
							r.operationID = "admin_users_destroy"
							r.pathPattern = "/api/v1/admin/users/{id}/"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = AdminUsersRetrieveOperation
							r.summary = "Retrieve a user by ID"
							r.operationID = "admin_users_retrieve"
							r.pathPattern = "/api/v1/admin/users/{id}/"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = AdminUsersUpdateOperation
							r.summary = "Update a user"
							r.operationID = "admin_users_update"
							r.pathPattern = "/api/v1/admin/users/{id}/"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'f': // Prefix: "facilities/"

				if l := len("facilities/"); len(elem) >= l && elem[0:l] == "facilities/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = FacilitiesListOperation
						r.summary = "List all public facilities"
						r.operationID = "facilities_list"
						r.pathPattern = "/api/v1/facilities/"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = FacilitiesCreateOperation
						r.summary = "Create a facility (admin only)"
						r.operationID = "facilities_create"
						r.pathPattern = "/api/v1/facilities/"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				// Param: "id"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = FacilitiesDestroyOperation
							r.summary = "Delete a facility (admin only)"
							r.operationID = "facilities_destroy"
							r.pathPattern = "/api/v1/facilities/{id}/"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = FacilitiesRetrieveOperation
							r.summary = "Retrieve facility details"
							r.operationID = "facilities_retrieve"
							r.pathPattern = "/api/v1/facilities/{id}/"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = FacilitiesPartialUpdateOperation
							r.summary = "Partially update a facility (admin only)"
							r.operationID = "facilities_partial_update"
							r.pathPattern = "/api/v1/facilities/{id}/"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = FacilitiesUpdateOperation
							r.summary = "Update a facility (admin only)"
							r.operationID = "facilities_update"
							r.pathPattern = "/api/v1/facilities/{id}/"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'm': // Prefix: "me/"

				if l := len("me/"); len(elem) >= l && elem[0:l] == "me/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = MeRetrieveOperation
						r.summary = "Retrieve current authenticated user"
						r.operationID = "me_retrieve"
						r.pathPattern = "/api/v1/me/"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			}

		}
	}
	return r, false
}
