// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AdminUsersCreate implements admin_users_create operation.
//
// Create a new user account. Admin access required.
//
// POST /api/v1/admin/users/
func (UnimplementedHandler) AdminUsersCreate(ctx context.Context, req *AdminUser) (r AdminUsersCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminUsersDestroy implements admin_users_destroy operation.
//
// Delete the user with the given ID. Admin access required.
//
// DELETE /api/v1/admin/users/{id}/
func (UnimplementedHandler) AdminUsersDestroy(ctx context.Context, params AdminUsersDestroyParams) (r AdminUsersDestroyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminUsersList implements admin_users_list operation.
//
// Retrieves a list of all registered users. Admin access required.
//
// GET /api/v1/admin/users/
func (UnimplementedHandler) AdminUsersList(ctx context.Context) (r AdminUsersListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminUsersPartialUpdate implements admin_users_partial_update operation.
//
// Update select fields of a user. Admin access required.
//
// PATCH /api/v1/admin/users/{id}/
func (UnimplementedHandler) AdminUsersPartialUpdate(ctx context.Context, req *AdminUserMergePatchUpdate, params AdminUsersPartialUpdateParams) (r AdminUsersPartialUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminUsersRetrieve implements admin_users_retrieve operation.
//
// Fetch details of a specific user by ID. Admin access required.
//
// GET /api/v1/admin/users/{id}/
func (UnimplementedHandler) AdminUsersRetrieve(ctx context.Context, params AdminUsersRetrieveParams) (r AdminUsersRetrieveRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminUsersUpdate implements admin_users_update operation.
//
// Update an existing user's full data by ID. Admin access required.
//
// PUT /api/v1/admin/users/{id}/
func (UnimplementedHandler) AdminUsersUpdate(ctx context.Context, req *AdminUser, params AdminUsersUpdateParams) (r AdminUsersUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FacilitiesCreate implements facilities_create operation.
//
// Creates a new facility. Only administrators are authorized.
//
// POST /api/v1/facilities/
func (UnimplementedHandler) FacilitiesCreate(ctx context.Context, req *PublicFacility) (r FacilitiesCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FacilitiesDestroy implements facilities_destroy operation.
//
// Deletes a facility. Only administrators are authorized.
//
// DELETE /api/v1/facilities/{id}/
func (UnimplementedHandler) FacilitiesDestroy(ctx context.Context, params FacilitiesDestroyParams) (r FacilitiesDestroyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FacilitiesList implements facilities_list operation.
//
// Returns a list of all active facilities. No authentication required.
//
// GET /api/v1/facilities/
func (UnimplementedHandler) FacilitiesList(ctx context.Context) (r []PublicFacility, _ error) {
	return r, ht.ErrNotImplemented
}

// FacilitiesPartialUpdate implements facilities_partial_update operation.
//
// Updates select fields of a facility. Only administrators are authorized.
//
// PATCH /api/v1/facilities/{id}/
func (UnimplementedHandler) FacilitiesPartialUpdate(ctx context.Context, req *PublicFacilityMergePatchUpdate, params FacilitiesPartialUpdateParams) (r FacilitiesPartialUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FacilitiesRetrieve implements facilities_retrieve operation.
//
// Returns detailed information about a specific facility. No authentication required.
//
// GET /api/v1/facilities/{id}/
func (UnimplementedHandler) FacilitiesRetrieve(ctx context.Context, params FacilitiesRetrieveParams) (r FacilitiesRetrieveRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FacilitiesUpdate implements facilities_update operation.
//
// Updates an existing facility. Only administrators are authorized.
//
// PUT /api/v1/facilities/{id}/
func (UnimplementedHandler) FacilitiesUpdate(ctx context.Context, req *PublicFacility, params FacilitiesUpdateParams) (r FacilitiesUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MeRetrieve implements me_retrieve operation.
//
// Returns basic profile information of the currently authenticated user.
//
// GET /api/v1/me/
func (UnimplementedHandler) MeRetrieve(ctx context.Context) (r MeRetrieveRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *UnexpectedErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *UnexpectedErrorStatusCode) {
	r = new(UnexpectedErrorStatusCode)
	return r
}
