// Code generated by ogen, DO NOT EDIT.
package api

type AdminUsersCreateRes interface {
	adminUsersCreateRes()
}

type AdminUsersDestroyRes interface {
	adminUsersDestroyRes()
}

type AdminUsersListRes interface {
	adminUsersListRes()
}

type AdminUsersPartialUpdateRes interface {
	adminUsersPartialUpdateRes()
}

type AdminUsersRetrieveRes interface {
	adminUsersRetrieveRes()
}

type AdminUsersUpdateRes interface {
	adminUsersUpdateRes()
}

type FacilitiesCreateRes interface {
	facilitiesCreateRes()
}

type FacilitiesDestroyRes interface {
	facilitiesDestroyRes()
}

type FacilitiesPartialUpdateRes interface {
	facilitiesPartialUpdateRes()
}

type FacilitiesRetrieveRes interface {
	facilitiesRetrieveRes()
}

type FacilitiesUpdateRes interface {
	facilitiesUpdateRes()
}

type MeRetrieveRes interface {
	meRetrieveRes()
}
