# Jekyll configuration for GitHub Pages

title: Facility Reservation API
description: A Go-based API for facility reservation management
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Theme
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

# Theme settings
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "//github.com/thara/facility_reservation_go"

# Footer content
footer_content: "Copyright &copy; 2024. Distributed by an <a href=\"https://github.com/thara/facility_reservation_go/blob/main/LICENSE\">MIT license.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Google Analytics
ga_tracking: # Add your tracking ID here if needed

# Navigation structure
nav_enabled: true
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
nav_external_links:
  - title: GitHub
    url: https://github.com/thara/facility_reservation_go

# Collections for docs
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      nav_enabled: true
      search_enabled: true

# Include/Exclude
include:
  - "*.md"
  - "adr/*.md"
  - "design-docs/*.md"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _site/