// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateFacility(ctx context.Context, db DBTX, arg CreateFacilityParams) (Facility, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (CreateUserRow, error)
	DeleteFacility(ctx context.Context, db DBTX, id int32) error
	DeleteUser(ctx context.Context, db DBTX, id int32) error
	GetCurrentUser(ctx context.Context, db DBTX, id int32) (GetCurrentUserRow, error)
	GetFacilityByID(ctx context.Context, db DBTX, id int32) (Facility, error)
	// Users queries for admin and authentication operations
	GetUserByID(ctx context.Context, db DBTX, id int32) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, db DBTX, username string) (User, error)
	ListAllFacilities(ctx context.Context, db DBTX) ([]Facility, error)
	// Facilities queries for public and admin operations
	ListFacilities(ctx context.Context, db DBTX) ([]Facility, error)
	ListUsers(ctx context.Context, db DBTX) ([]ListUsersRow, error)
	UpdateFacility(ctx context.Context, db DBTX, arg UpdateFacilityParams) (Facility, error)
	UpdateFacilityPartial(ctx context.Context, db DBTX, arg UpdateFacilityPartialParams) (Facility, error)
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserPassword(ctx context.Context, db DBTX, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
