// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	CreateFacility(ctx context.Context, arg CreateFacilityParams) (Facility, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (UserToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFacility(ctx context.Context, id int32) error
	DeleteToken(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetFacilityByID(ctx context.Context, id int32) (Facility, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Users queries for Phase 1 token-based authentication
	GetUserByToken(ctx context.Context, token string) (GetUserByTokenRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAllFacilities(ctx context.Context) ([]Facility, error)
	// Facilities queries for public and admin operations
	ListFacilities(ctx context.Context) ([]Facility, error)
	ListUserTokens(ctx context.Context, userID uuid.UUID) ([]UserToken, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateFacility(ctx context.Context, arg UpdateFacilityParams) (Facility, error)
	UpdateFacilityPartial(ctx context.Context, arg UpdateFacilityPartialParams) (Facility, error)
}

var _ Querier = (*Queries)(nil)
